#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
----------------------------------------------------------------------
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
    echo "Executing usermod..."
    mkdir "/tmp/temphome"
    usermod -d "/tmp/temphome" hotio
    usermod -o -u "${PUID}" hotio
    usermod -d "${CONFIG_DIR}" hotio
    rm -rf "/tmp/temphome"
    groupmod -o -g "${PGID}" hotio
else
    echo "Running as root is not supported, please fix your PUID and PGID!"
    exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown hotio:hotio "${CONFIG_DIR}"

ln -s -f -n "${CONFIG_DIR}/" "${CONFIG_DIR}/.stash"
chown -h hotio:hotio "${CONFIG_DIR}/.stash"

if [[ ! -e "${CONFIG_DIR}/.stash/ffmpeg" ]]; then
    ln -s "$(command -v ffmpeg)" "${CONFIG_DIR}/.stash/ffmpeg"
    chown -h hotio:hotio "${CONFIG_DIR}/.stash/ffmpeg"
fi

if [[ ! -e "${CONFIG_DIR}/.stash/ffprobe" ]]; then
    ln -s "$(command -v ffprobe)" "${CONFIG_DIR}/.stash/ffprobe"
    chown -h hotio:hotio "${CONFIG_DIR}/.stash/ffprobe"
fi
