#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"

ln -s -f -n "${CONFIG_DIR}/" "${CONFIG_DIR}/.stash"
find "${CONFIG_DIR}/.stash" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown -h hotio:hotio {} +

if [[ ! -e "${CONFIG_DIR}/.stash/ffmpeg" ]]; then
    ln -s "$(command -v ffmpeg)" "${CONFIG_DIR}/.stash/ffmpeg"
    find "${CONFIG_DIR}/.stash/ffmpeg" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown -h hotio:hotio {} +
fi

if [[ ! -e "${CONFIG_DIR}/.stash/ffprobe" ]]; then
    ln -s "$(command -v ffprobe)" "${CONFIG_DIR}/.stash/ffprobe"
    find "${CONFIG_DIR}/.stash/ffprobe" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown -h hotio:hotio {} +
fi
