#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
HOME="${CONFIG_DIR}" redirect_cmd exec s6-setuidgid hotio "${APP_DIR}/stash" --config "${CONFIG_DIR}/app/config.yml" ${ARGS}
